# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 652288e8d6bea717804c4c219186f4420e4de575a5f4ba96c806fce5d5e3096eaaa404bfbd3832950c690623fb742d2f255c5e422131f25982294524c886e288

test:
  secret_key_base: df437e45f836bd0b0ffa1ed9014ea7c664d70e1e5393754d4bd8e1091829915b77585feb348bbbb50328f3db165214efb8c282605b1631549cff455a85dc7ce3

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
